# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('Silicon Valley', 'Silicon Valley'), ('Seatle', 'Seatle'), ('Los Angelos', 'Los Angelos'), ('Dallas', 'Dallas'), ('Washington DC', 'Washington DC'), ('Chicago', 'Chicago'), ('Tulsa', 'Tulsa'), ('New York', 'New York')], max_length=255)),
                ('state', models.CharField(choices=[('CA', 'California'), ('WA', 'Washington'), ('TX', 'Texas'), ('VA', 'Virginia'), ('IL', 'Illinois'), ('OK', 'Oklahoma'), ('NY', 'New York')], max_length=255)),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dojo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninjas.Dojo')),
            ],
        ),
    ]
