# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_card_app', '0002_auto_20170925_1709'),
        ('login_registration_app', '0001_initial'),
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='credit_card_app.CreditCard')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='service_app.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='login_registration_app.User')),
            ],
        ),
    ]
