# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
        ('driver_license_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='license', to='login_registration_app.User'),
            preserve_default=False,
        ),
    ]
