# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
