# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books_app', '0002_auto_20170920_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='likes_books_app.User'),
        ),
    ]
