# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170925_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='User',
            new_name='user',
        ),
    ]
