# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='users',
        ),
        migrations.AddField(
            model_name='books',
            name='users',
            field=models.ManyToManyField(related_name='books', to='queries.User'),
        ),
    ]
