# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_auto_20170919_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='users',
            field=models.ManyToManyField(related_name='book', to='queries.User'),
        ),
    ]
