# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0006_auto_20170920_0835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
