# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_date_to',
            field=models.DateField(),
        ),
    ]
